# Generated by Django 6.0.5 on 2026-05-22 09:18

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civilite', models.CharField(choices=[('M.', 'Monsieur'), ('Mme', 'Madame'), ('Mlle', 'Mademoiselle')], default='M.', max_length=10)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('telephone', models.CharField(blank=True, max_length=30)),
                ('adresse', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['nom', 'prenom'],
            },
        ),
        migrations.CreateModel(
            name='ParametresHotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Hôtel pacific', max_length=100)),
                ('adresse', models.CharField(default='28 Rue Royale', max_length=200)),
                ('code_postal', models.CharField(default='62100', max_length=10)),
                ('ville', models.CharField(default='Calais', max_length=100)),
                ('telephone', models.CharField(default='+33 668401405', max_length=30)),
                ('email', models.EmailField(default='pacifichotel62@gmail.com', max_length=254)),
                ('siret', models.CharField(default='837873785', max_length=20)),
                ('capital', models.CharField(default='1000 €', max_length=20)),
                ('tva_defaut', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Taux de TVA par défaut (%)', max_digits=5)),
                ('taxe_sejour_defaut', models.DecimalField(decimal_places=2, default=Decimal('0.98'), help_text='Taxe de séjour par nuit/personne (€)', max_digits=6)),
                ('prix_chambre_defaut', models.DecimalField(decimal_places=2, default=Decimal('52.96'), help_text='Prix chambre HT par nuit (€)', max_digits=8)),
            ],
            options={
                'verbose_name': "Paramètres de l'hôtel",
                'verbose_name_plural': "Paramètres de l'hôtel",
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_reservation', models.PositiveIntegerField(unique=True)),
                ('date_arrivee', models.DateField()),
                ('date_depart', models.DateField()),
                ('date_edition', models.DateField()),
                ('numero_chambre', models.PositiveIntegerField(default=1)),
                ('nombre_personnes', models.PositiveIntegerField(default=1)),
                ('type_sejour', models.CharField(default='Standard Normal', max_length=100)),
                ('prix_chambre_ht', models.DecimalField(decimal_places=2, help_text='Prix HT par nuit', max_digits=8)),
                ('taxe_sejour_unitaire', models.DecimalField(decimal_places=2, default=Decimal('0.98'), help_text='Taxe séjour par nuit et par personne', max_digits=6)),
                ('taux_tva', models.DecimalField(decimal_places=2, default=Decimal('2.00'), help_text='Taux de TVA en %', max_digits=5)),
                ('extras', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8)),
                ('statut', models.CharField(choices=[('PROVISOIRE', 'Document provisoire'), ('DEFINITIF', 'Facture définitive'), ('ACQUITTE', 'Facture acquittée')], default='PROVISOIRE', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('cree_le', models.DateTimeField(auto_now_add=True)),
                ('modifie_le', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='factures', to='factures.client')),
            ],
            options={
                'verbose_name': 'Facture',
                'verbose_name_plural': 'Factures',
                'ordering': ['-cree_le'],
            },
        ),
    ]
