# Generated by Django 5.1.15 on 2026-06-09 16:09

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factures", "0002_client_societe"),
    ]

    operations = [
        migrations.AddField(
            model_name="client",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="client",
            name="pays",
            field=models.CharField(blank=True, default="France", max_length=100),
        ),
        migrations.AddField(
            model_name="client",
            name="ville",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="facture",
            name="date_paiement",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="facture",
            name="moyen_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non spécifié"),
                    ("Especes", "Espèces"),
                    ("Carte bancaire", "Carte bancaire"),
                    ("Virement", "Virement"),
                    ("Cheque", "Chèque"),
                    ("Booking", "Booking / plateforme"),
                    ("Non paye", "Non payé"),
                ],
                max_length=20,
                verbose_name="Moyen de paiement",
            ),
        ),
        migrations.AddField(
            model_name="facture",
            name="taux_taxe_sejour",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Taux de taxe de séjour en % du montant HT",
                max_digits=5,
            ),
        ),
        migrations.AddField(
            model_name="parametreshotel",
            name="nombre_chambres",
            field=models.PositiveIntegerField(
                default=10,
                help_text="Nombre total de chambres (pour statistiques d'occupation)",
            ),
        ),
        migrations.AddField(
            model_name="parametreshotel",
            name="taxe_sejour_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Taxe de séjour en pourcentage du montant HT (%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="client",
            name="civilite",
            field=models.CharField(
                choices=[
                    ("M.", "Monsieur"),
                    ("Mme", "Madame"),
                    ("Mlle", "Mademoiselle"),
                    ("Société", "Société"),
                ],
                default="M.",
                max_length=10,
            ),
        ),
    ]
