# Generated by Django 5.1.15 on 2026-06-09 16:28

import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factures", "0003_client_notes_client_pays_client_ville_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Extra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100, verbose_name="Nom")),
                (
                    "prix_defaut",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=8,
                        verbose_name="Prix par défaut",
                    ),
                ),
                ("actif", models.BooleanField(default=True, verbose_name="Actif")),
            ],
            options={
                "verbose_name": "Extra / Service",
                "verbose_name_plural": "Extras / Services",
                "ordering": ["nom"],
            },
        ),
        migrations.AlterField(
            model_name="facture",
            name="date_edition",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name="facture",
            name="extras",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                help_text="Ancien champ Extras (remplacé par FactureExtra)",
                max_digits=8,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="numero_reservation",
            field=models.PositiveIntegerField(
                blank=True, null=True, unique=True, verbose_name="N° réservation"
            ),
        ),
        migrations.CreateModel(
            name="FactureExtra",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "prix_unitaire",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Prix unitaire"
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2,
                        editable=False,
                        max_digits=10,
                        verbose_name="Total",
                    ),
                ),
                (
                    "extra",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="factures.extra",
                        verbose_name="Extra",
                    ),
                ),
                (
                    "facture",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="facture_extras",
                        to="factures.facture",
                    ),
                ),
            ],
            options={
                "verbose_name": "Extra de facture",
                "verbose_name_plural": "Extras de facture",
            },
        ),
    ]
