# Generated by Django 5.1.15 on 2026-06-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factures", "0004_extra_alter_facture_date_edition_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="client",
            name="email",
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name="client",
            name="telephone",
            field=models.CharField(max_length=30),
        ),
    ]
