# Generated by Django 5.1.15 on 2026-06-09 16:58

from django.db import migrations


def seed_extras(apps, schema_editor):
    Extra = apps.get_model('factures', 'Extra')
    v = 'V\u00e9lo'
    p = 'Petit-d\u00e9jeuner'
    defaults = [
        (v, 10.00),
        ('Parking', 5.00),
        (p, 8.00),
    ]
    for nom, prix in defaults:
        Extra.objects.get_or_create(nom=nom, defaults={'prix_defaut': prix, 'actif': True})


class Migration(migrations.Migration):

    dependencies = [
        ("factures", "0005_alter_client_email_alter_client_telephone"),
    ]

    operations = [
        migrations.RunPython(seed_extras),
    ]
