# Generated by Django 5.1.15 on 2026-06-09 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("factures", "0006_seed_default_extras"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facture",
            name="date_paiement",
        ),
    ]
