# Generated by Django 5.1.15 on 2026-06-09 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factures", "0007_remove_facture_date_paiement"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="moyen_paiement",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "Non spécifié"),
                    ("Especes", "Espèces"),
                    ("Carte bancaire", "Carte bancaire"),
                    ("Virement", "Virement"),
                    ("Cheque", "Chèque"),
                    ("Booking", "Booking / plateforme"),
                ],
                max_length=20,
                verbose_name="Moyen de paiement",
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="numero_reservation",
            field=models.CharField(
                blank=True,
                max_length=20,
                null=True,
                unique=True,
                verbose_name="N° réservation",
            ),
        ),
    ]
