# Generated by Django 5.1.15 on 2026-06-11 14:00

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factures", "0008_alter_facture_moyen_paiement_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="facture",
            name="taux_taxe_sejour",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.00"),
                help_text="Taux de taxe de séjour en % du montant HT",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="facture",
            name="taux_tva",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Taux de TVA en %",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="parametreshotel",
            name="taxe_sejour_pourcentage",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("2.00"),
                help_text="Taxe de séjour en pourcentage du montant HT (%)",
                max_digits=5,
            ),
        ),
        migrations.AlterField(
            model_name="parametreshotel",
            name="tva_defaut",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("10.00"),
                help_text="Taux de TVA par défaut (%)",
                max_digits=5,
            ),
        ),
    ]
