# Generated by Django 5.1.15 on 2026-06-30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("factures", "0009_alter_facture_taux_taxe_sejour_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parametreshotel",
            name="fax",
            field=models.CharField(
                blank=True, default="0321975802", max_length=30
            ),
        ),
        migrations.AlterField(
            model_name="parametreshotel",
            name="adresse",
            field=models.CharField(default="40 rue du duc de guise", max_length=200),
        ),
        migrations.AlterField(
            model_name="parametreshotel",
            name="email",
            field=models.EmailField(default="sunetap.yahi@gmail.com", max_length=254),
        ),
        migrations.AlterField(
            model_name="parametreshotel",
            name="telephone",
            field=models.CharField(default="0321345024", max_length=30),
        ),
    ]
